services:
  kafka:
    image: "quay.io/ogunalp/kafka-native:0.9.0-kafka-3.7.0"
    ports:
      - "9092:9092"
  kafka-populator:
    build: ./kafka-populator
    depends_on:
      - kafka
  jobmanager:
    build: ./custom-flink
    depends_on:
      - kafka-populator
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
  taskmanager:
    build: ./custom-flink
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2        
  apicurioregistry:
    image: apicurio/apicurio-registry-kafkasql:2.6.0.Final
    hostname: apicurio
    container_name: apicurio
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  apicurio-populate:
    build: .
    depends_on:
      - kafka-populator
      - apicurioregistry
  sql-client:
    build: ./custom-flink
    command: bin/sql-client.sh
    depends_on:
      - taskmanager
      - apicurio-populate
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
